### ISSUE TITLE
Editing documentation for Class PP

### ISSUE THREAD

**Issue by geopet** [documenting-ruby/ruby#10]
I'm making some minor changes to the pp class documentation.

**Comment by zzak** [comment]
@geopet Great, let me know if you have any questions or need a review!

**Comment by zzak** [comment]
@geopet I've written a short example to implement pretty print using PP::ObjectMixin: https://gist.github.com/zzak/5479679

Let me know if you have any questions!

**Comment by geopet** [comment]
@zzak Awesome! I've looked it over and commented on my utter confusion on the topic. It's an authentic: "It's not you, it's me." situation there. :confounded: :grinning:

**Comment by zzak** [comment]
@geopet Thanks for the ping, I'll get back to you here, because apparently github doesn't notify you when someone comments on a gist. :(

**Comment by zzak** [comment]
@geopet The `inspect` alias is to override Object#inspect with the pretty print version.

I agree the current docs are confusing, but I think a good use case would alleviate this. The PP::ObjectMixin docs seem sort of implementation specific.

My example is short, so maybe we can provide a more useful example at some point.

The purpose of my example is to implement PP in my class, so that I can easily customize the output of my class. Without having the user require PP and pretty print their Cat instances on their own. That is the obvious benefit for my use case. I'm sure you could expand on this to print more elaborate objects and data structures, but I don't have any ideas on this.

**Comment by zzak** [comment]
@geopet I think I'm going to use my example for PP::ObjectMixin in another demonstration, if you don't mind. I will be patching the docs for this module, but only adding a basic introduction with that example.
