### ISSUE TITLE
Adding Aliased as to detect and find enumerables

### ISSUE THREAD

**Issue by ghost** [documenting-ruby/ruby#43]
As in the Array ruby docs, identical methods are listed as "Alias for: method name".  For example in the Array docs there are two identical methods: length, and size.  It is indicated that in both methods that they Alias for: length and Alias for: size.  This is very helpful to the Dev in that it is immediately known that both methods act the exact same way when used; more over, that either method can be used safely knowing the outcome, just adding more linguistic control over code read.

**Comment by zzak** [comment]
@revspringjake Since detect/find are not actually aliases, but defined as the same method they are treated differently by Ruby and RDoc. That said, in #34 both of these methods will show up under the same method definition in future releases of Ruby.

Thank you for the report and let me know if you have any other questions! <3
