### ISSUE TITLE
enumerable: collect_concat documents flat_map

### ISSUE THREAD

**Issue by tibbon** [documenting-ruby/ruby#46]
The `collect` and `map` documentation are the same, and show examples of each to enforce this. There's no mention however that they are aliases for the same code (but that's another issue for later). 

However the `collect_concat` and `flat_map` documentation only shows examples of code using `flat_map`. There's no mention that these one is an alias for another, and the example never shows `collect_concat`. 

I propose (and will file a PR) that we have one example of `collect_concat` and one of `flat_map` to demonstrate that these are the same. Otherwise, looking at the documentation for `collect_concat` and not seeing a code example of it being used is confusing and inconsistent.

**Comment by zzak** [comment]
@tibbon Thank you for your report.

This is because both of these methods are aliased. RDoc (the documentation generator for ruby) has historically had issues with displaying aliased methods. However, this should be resolved in recent releases of the library.

With that said, if an aliased method is not also included in the method signature for a method in ruby, I'd welcome a patch for that. For example:

``` c
/*
 * call-seq:
 *    enum.collect { ... } -> array
 *    enum.map { ... } -> array
 *    ...
 */
```

You can see the `call-seq` (or method signature) shares both of the aliases.
